import mongoose from "mongoose";

const customerKycSchema = new mongoose.Schema({
  category: String,
  name_of_individual: String,
  status: String,
  factory_addresses: [
    {
      factory_address_line_1: String,
      factory_address_line_2: String,
      factory_address_city: String,
      factory_address_state: String,
      factory_address_pin_code: String,
    },
  ],
  permanent_address_line_1: String,
  permanent_address_line_2: String,
  permanent_address_city: String,
  permanent_address_state: String,
  permanent_address_pin_code: String,
  permanent_address_telephone: String,
  permanent_address_email: String,
  principle_business_address_line_1: String,
  principle_business_address_line_2: String,
  principle_business_address_city: String,
  principle_business_address_state: String,
  principle_business_address_pin_code: String,
  principle_address_email: String,
  principle_business_telephone: String,
  principle_business_website: String,
  authorised_signatories: [{ type: String }],
  authorisation_letter: [{ type: String }],
  iec_no: String,
  pan_no: String,
  banks: [
    {
      bankers_name: String,
      branch_address: String,
      account_no: String,
      ifsc: String,
      ad_code: String,
    },
  ],
  passport_img: String,
  voter_card_img: String,
  driving_license_img: String,
  bank_statement_img: String,
  ration_card_img: String,
  registration_certificate_img: String,
  partnership_deed_img: String,
  power_of_attorney_partnership_img: String,
  partnership_valid_document: String,
  partnership_aadhar_card_front_photo: String,
  partnership_aadhar_card_back_photo: String,
  telephone_bill_in_the_name_of_firm_img: String,
  certificate_of_incorporation_img: String,
  memorandum_of_association_img: String,
  articles_of_association_img: String,
  power_of_attorney_company_img: String,
  telephone_bill_company_img: String,
  pan_allotment_letter_img: String,
  certificate_of_registration_img: String,
  power_of_attorney_trust_img: String,
  officially_valid_document_trust_img: String,
  resolution_of_managing_body_img: String,
  telephone_bill_trust_img: String,
  name_of_trustees: String,
  name_of_founder: String,
  address_of_founder: String,
  telephone_of_founder: String,
  email_of_founder: String,
  approval: String,
});

const customerKyc = mongoose.model("customerKyc", customerKycSchema);
export default customerKyc;
