import mongoose from "mongoose";

const kycSchema = new mongoose.Schema({
  employee_id: { type: String },
  first_name: { type: String },
  middle_name: { type: String },
  last_name: { type: String },
  designation: { type: String },
  department: { type: String },
  joining_date: { type: String },
  permanent_address_line_1: { type: String },
  permanent_address_line_2: { type: String },
  permanent_address_city: { type: String },
  permanent_address_state: { type: String },
  permanent_address_pincode: { type: String },
  communication_address_line_1: { type: String },
  communication_address_line_2: { type: String },
  communication_address_city: { type: String },
  communication_address_state: { type: String },
  communication_address_pincode: { type: String },
  personal_email: { type: String },
  official_email: { type: String },
  dob: { type: String },
  mobile: { type: String },
  emergency_contact: { type: String },
  emergency_contact_name: { type: String },
  family_members: [{ type: String }],
  employee_photo: { type: String },
  close_friend_contact_no: { type: String },
  blood_group: { type: String },
  highest_qualification: { type: String },
  aadhar_no: { type: String },
  aadhar_photo_front: { type: String },
  aadhar_photo_back: { type: String },
  pan_no: { type: String },
  pan_photo: { type: String },
  insurance_status: [{ type: String }],
  license_front: { type: String },
  license_back: { type: String },
  bank_account_no: { type: String },
  bank_name: { type: String },
  ifsc_code: { type: String },
  favorite_song: { type: String },
  marital_status: { type: String },
  pf_no: { type: String },
  esic_no: { type: String },
  approval: {
    type: String,
  },
});

const kyc = mongoose.model("Kyc", kycSchema);
export default kyc;
